name: app
description: app customer app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.6+31

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  csc_picker: ^0.2.7
  #Date Picker
  flutter_rounded_date_picker: ^3.0.2
  flutter_localization: ^0.1.10
  intl: any
  #animations
  animations: ^2.0.3
  cupertino_stepper: ^0.2.1
  flutter_switch: ^0.3.2
  animated_splash_screen: ^1.3.0
  #spinKit
  flutter_spinkit: ^5.1.0
  #qr Code
  qr_flutter: ^4.0.0
  barcode_scan2: ^4.2.1
  # GET
  get: 4.6.5
  get_storage: 2.0.3
  # DIO
  dio: 4.0.6
  dio_http_cache: 0.3.0
  # FONT
  google_fonts: 3.0.1
  font_awesome_flutter: ^10.4.0
  #IMAGES, SLIDERS, LAYOUTS
  flutter_cache_manager: 3.3.0
  cached_network_image: 3.2.2
  carousel_slider: 4.1.1
  flutter_svg: 1.1.5
  flutter_staggered_grid_view: 0.6.2
  image_picker: 0.8.6
  cupertino_icons: any
  shimmer: 2.0.0
  intl_phone_field: 3.1.0
  # WEB
  webview_flutter: 3.0.4
  flutter_html: 3.0.0-alpha.3
  url_launcher: 6.1.6
  http: ^0.13.4
  # DROPDDOWN SEARCH
  dropdown_search: ^5.0.6
  # FIREBASE
  firebase_messaging: 13.1.0
  cloud_firestore: 3.5.1
  flutter_local_notifications: ^12.0.3
  firebase_auth: 3.11.2
  firebase_core: 1.24.0
  firebase_storage: 10.3.11
  # GOOGLE MAPS
  google_sign_in: ^5.4.0
  google_maps_flutter: 2.2.1
  google_maps_flutter_web: 0.4.0+3
  map_launcher: 2.4.0
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.16
  google_maps_place_picker_mb:
    git:
      url: https://github.com/SmarterVision/google_maps_place_picker_mb.git
      ref: 2.0.0-mb.22
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  fluttertoast: ^8.2.2
  data_table_2: ^2.4.2
  webview_flutter_plus: ^0.3.0+2
  change_app_package_name: ^1.1.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  flutter_gcaptcha_v3: ^2.0.0
  g_recaptcha_v3: ^0.0.5
  app_settings: ^4.2.0
  video_player: ^2.7.0
  lottie: ^2.3.2
  flutter_rating_bar: ^4.0.1
  printing: ^5.9.3
  pdf: ^3.8.4
  web_socket_channel: ^2.4.0
  flutter_localizations:
    sdk: flutter
  package_info_plus: ^1.0.6
  multiselect: ^0.1.0
  im_stepper: ^1.0.1+1




dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.9.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  image_path: "assets/img/hubcolis.png"
  android: true
  ios: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - config/
    - assets/img/
    - assets/icon/
    - assets/webpage/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
